# Generated by Django 5.0.3 on 2024-03-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating_average', models.FloatField()),
                ('rating_count', models.FloatField()),
            ],
        ),
    ]
